# Landslide Datasets

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import warnings
warnings.filterwarnings("ignore")

pd.set_option('display.max_columns', None)

## Global Landslide Catalog (GLC) - Kaggle Dataset
(compiled since 2007 at NASA Goddard Space Flight Center)

Landslides After Rainfall, 2007-2016  
Location and cause of landslide events around the world  

NASA
- updated 3 years ago (Version 1)

https://www.kaggle.com/nasa/landslide-events

Context  
Landslides are one of the most pervasive hazards in the world, causing more than 11,500 fatalities in 70 countries since 2007. Saturating the soil on vulnerable slopes, intense and prolonged rainfall is the most frequent landslide trigger.

Content  
The Global Landslide Catalog (GLC) was developed with the goal of identifying rainfall-triggered landslide events around the world, regardless of size, impacts, or location. The GLC considers all types of mass movements triggered by rainfall, which have been reported in the media, disaster databases, scientific reports, or other sources.

Acknowledgements  
The GLC has been compiled since 2007 at NASA Goddard Space Flight Center.

Data Sources  
catalog.csv   23 columns  

About this file  
Landslide events caused by rainfall  

Columns  

- id
- date
- time
- continent_code
- country_name
- country_code
- state/province
- population
- city/town
- distance
- location_description
- latitude
- longitude
- geolocation
- hazard_type
- landslide_type
- landslide_size
- trigger
- storm_name
- injuries
- fatalities
- source_name
- source_link

In [2]:
ls_glc_nasa = pd.read_csv(r'Datasets/catalog.csv')

**Checking dataset information - Features and ammount of data**

In [3]:
ls_glc_nasa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1693 entries, 0 to 1692
Data columns (total 23 columns):
id                      1693 non-null int64
date                    1690 non-null object
time                    629 non-null object
continent_code          164 non-null object
country_name            1693 non-null object
country_code            1693 non-null object
state/province          1692 non-null object
population              1693 non-null int64
city/town               1689 non-null object
distance                1692 non-null float64
location_description    551 non-null object
latitude                1692 non-null float64
longitude               1692 non-null float64
geolocation             1692 non-null object
hazard_type             1693 non-null object
landslide_type          1692 non-null object
landslide_size          1692 non-null object
trigger                 1691 non-null object
storm_name              132 non-null object
injuries                515 non-null float64
fatalities              1446 non-null float64
source_name             872 non-null object
source_link             1593 non-null object
dtypes: float64(5), int64(2), object(16)
memory usage: 304.3+ KB

**Data starts in 2007/March up to 2016/March**

In [4]:
ls_glc_nasa.head()

,id,date,time,continent_code,country_name,country_code,state/province,population,city/town,distance,location_description,latitude,longitude,geolocation,hazard_type,landslide_type,landslide_size,trigger,storm_name,injuries,fatalities,source_name,source_link
0,34,3/2/07,Night,NaN,United States,US,Virginia,16000,Cherry Hill,3.40765,Unknown,38.6009,-77.2682,"(38.600900000000003, -77.268199999999993)",Landslide,Landslide,Small,Rain,NaN,NaN,NaN,NBC 4 news,http://www.nbc4.com/news/11186871/detail.html
1,42,3/22/07,NaN,NaN,United States,US,Ohio,17288,New Philadelphia,3.33522,NaN,40.5175,-81.4305,"(40.517499999999998, -81.430499999999995)",Landslide,Landslide,Small,Rain,NaN,NaN,NaN,Canton Rep.com,http://www.cantonrep.com/index.php?ID=345054&C...
2,56,4/6/07,NaN,NaN,United States,US,Pennsylvania,15930,Wilkinsburg,2.91977,Urban area,40.4377,-79.9160,"(40.4377, -79.915999999999997)",Landslide,Landslide,Small,Rain,NaN,NaN,NaN,The Pittsburgh Channel.com,https://web.archive.org/web/20080423132842/htt...
3,59,4/14/07,NaN,NaN,Canada,CA,Quebec,42786,Ch√¢teauguay,2.98682,Above river,45.3226,-73.7771,"(45.322600000000001, -73.777100000000004)",Landslide,Riverbank collapse,Small,Rain,NaN,NaN,NaN,Le Soleil,http://www.hebdos.net/lsc/edition162007/articl...
4,61,4/15/07,NaN,NaN,United States,US,Kentucky,6903,Pikeville,5.66542,Below road,37.4325,-82.4931,"(37.432499999999997, -82.493099999999998)",Landslide,Landslide,Small,Downpour,NaN,NaN,0.0,Matthew Crawford (KGS),NaN

In [5]:
ls_glc_nasa.tail()

,id,date,time,continent_code,country_name,country_code,state/province,population,city/town,distance,location_description,latitude,longitude,geolocation,hazard_type,landslide_type,landslide_size,trigger,storm_name,injuries,fatalities,source_name,source_link
1688,7535,12/7/15,NaN,NaN,United States,US,North Carolina,1646,Tryon,7.80866,Above road,35.2219,-82.3226,"(35.221899999999998, -82.322599999999994)",Landslide,Rockfall,Small,NaN,NaN,0.0,0.0,Tryon Daily Bulletin,http://www.tryondailybulletin.com/2016/02/26/u...
1689,7537,2/22/16,0:00,NaN,United States,US,West Virginia,51400,Charleston,6.84721,Natural slope,38.3987,-81.5848,"(38.398699999999998, -81.584800000000001)",Landslide,Mudslide,Small,Unknown,NaN,0.0,0.0,Charleston Gazette,http://www.wvgazettemail.com/news/20160222/us-...
1690,7539,2/23/16,NaN,NaN,United States,US,West Virginia,2406,Welch,14.19735,Above road,37.4096,-81.4268,"(37.409599999999998, -81.4268)",Landslide,Landslide,Small,Rain,NaN,0.0,0.0,Bluefield Daily Telegraph,http://www.bdtonline.com/news/officials-cautio...
1691,7540,2/26/16,21:06,NaN,United States,US,West Virginia,1048,Athens,12.00678,Above road,37.5011,-81.1093,"(37.501100000000001, -81.109300000000005)",Landslide,Rockfall,Small,Unknown,NaN,0.0,0.0,Bluefield Daily Telegraph,http://www.bdtonline.com/news/rockslide-snarls...
1692,7541,3/2/16,8:00,NaN,United States,US,Vermont,2066,Windsor,1.78429,Above road,43.4771,-72.4066,"(43.4771, -72.406599999999997)",Landslide,Rockfall,Small,Unknown,NaN,0.0,0.0,Valley News,http://www.vnews.com/home/21353539-95/loose-ledge

**Landslide by Countries**

In [6]:
ls_glc_nasa.country_name.value_counts()

United States                       986
Colombia                             96
Guatemala                            79
Costa Rica                           75
Mexico                               73
Trinidad and Tobago                  63
Panama                               40
Honduras                             38
Jamaica                              33
Nicaragua                            31
Ecuador                              30
El Salvador                          22
Haiti                                20
Venezuela                            20
Dominican Republic                   15
Peru                                 14
Dominica                             14
Canada                               10
Saint Lucia                           8
Puerto Rico                           7
Brazil                                4
Saint Vincent and the Grenadines      4
Cuba                                  3
U.S. Virgin Islands                   2
Bermuda                               2
Grenada                               2
Barbados                              1
Belize                                1
Name: country_name, dtype: int64

**Landslides reported in Brazil**

In [7]:
ls_glc_nasa[(ls_glc_nasa.country_code == 'BR')]

,id,date,time,continent_code,country_name,country_code,state/province,population,city/town,distance,location_description,latitude,longitude,geolocation,hazard_type,landslide_type,landslide_size,trigger,storm_name,injuries,fatalities,source_name,source_link
192,1019,5/6/09,NaN,SA,Brazil,BR,Par√°,70888,Altamira,1.01848,NaN,-3.1946,-52.2093,"(-3.1945999999999999, -52.209299999999999)",Landslide,Mudslide,Medium,Rain,NaN,NaN,19.0,NaN,http://en.wikipedia.org/wiki/2009_Brazilian_fl...
193,1020,5/6/09,NaN,SA,Brazil,BR,Maranh√£o,48901,Barra do Corda,61.75306,NaN,-5.0804,-45.6010,"(-5.0804, -45.600999999999999)",Landslide,Mudslide,Medium,Rain,NaN,NaN,3.0,NaN,http://www.3news.co.nz/Heavy-rains-leave-186K-...
946,4789,3/28/13,0:30:00,SA,Brazil,BR,Amap√°,83927,Santana,0.17020,NaN,-0.0568,-51.1818,"(-0.056800000000000003, -51.181800000000003)",Landslide,Landslide,Medium,Other,NaN,NaN,6.0,bestonlinebroker.co,http://bestonlinebroker.co/p/3999693490/2013/0...
1347,6591,1/4/14,NaN,SA,Brazil,BR,Par√°,78050,Abaetetuba,1.04062,Urban area,-1.7225,-48.8907,"(-1.7224999999999999, -48.890700000000002)",Landslide,Riverbank collapse,Medium,Unknown,NaN,0.0,0.0,G1,http://g1.globo.com/pa/para/noticia/2014/01/ar...

**Landslide Types**

In [8]:
ls_glc_nasa.hazard_type.value_counts()

Landslide    1693
Name: hazard_type, dtype: int64

In [9]:
ls_glc_nasa.landslide_type.value_counts()

Landslide             866
Mudslide              635
Rockfall               70
Complex                48
Debris flow            38
Other                  14
Creep                   5
Riverbank collapse      5
mudslide                4
Snow avalanche          2
Lahar                   2
landslide               1
Unknown                 1
Rockslide               1
Name: landslide_type, dtype: int64

**Landslide Sizes**

In [10]:
ls_glc_nasa.landslide_size.value_counts()

Medium        965
Small         636
Large          68
Very_large     15
medium          3
small           3
large           2
Name: landslide_size, dtype: int64

**Landslide Triggers**

In [11]:
ls_glc_nasa.trigger.value_counts()

Downpour                   866
Rain                       446
Tropical cyclone           131
Continuous rain             95
Unknown                     88
unknown                     12
Snowfall snowmelt           11
Flooding                    10
Earthquake                   8
Mining digging               7
Freeze thaw                  6
Construction                 5
Other                        3
Volcano                      1
downpour                     1
Dam embankment collapse      1
Name: trigger, dtype: int64

## National Emergency Management Information System - Kaggle Dataset
(Federal Emergency Management Agency - FEMA - with data from the National Emergency Management Information System)

Federal Emergencies and Disasters, 1953-Present  

Has the number of emergencies declared by the president risen over time?  

Federal Emergency Management Agency (FEMA)
- updated 3 years ago (Version 1)

Context  
The president can declare an emergency for any occasion or instance when the President determines federal assistance is needed. Emergency declarations supplement State and local or Indian tribal government efforts in providing emergency services, such as the protection of lives, property, public health, and safety, or to lessen or avert the threat of a catastrophe in any part of the United States. The total amount of assistance provided for in a single emergency may not exceed $5 million.

Content  
This dataset includes a record for every federal emergency or disaster declared by the President of the United States since 1953.

Acknowledgements  
The disaster database was published by the Federal Emergency Management Agency with data from the National Emergency Management Information System.

Inspiration  
What type of disaster is the most commonly declared by FEMA? Which disasters or emergencies have lasted the longest? What disaster was declared in the most counties or states? Has the number of disasters declared by FEMA risen or fallen over time?
The president can declare a major disaster for any natural event, including any hurricane, tornado, storm, high water, wind-driven water, tidal wave, tsunami, earthquake, volcanic eruption, landslide, mudslide, snowstorm, or drought, or, regardless of cause, fire, flood, or explosion, that the President determines has caused damage of such severity that it is beyond the combined capabilities of state and local governments to respond. A major disaster declaration provides a wide range of federal assistance programs for individuals and public infrastructure, including funds for both emergency and permanent work.

Data Sources
database.csv - 14 columns  

About this file  
Federal emergencies and disasters

Columns  

- Declaration Number
- Declaration Type
- Declaration Date
- State
- County
- Disaster Type
- Disaster Title
- Start Date
- End Date
- Close Date
- Individual Assistance Program
- Individuals & Households Program
- Public Assistance Program
- Hazard Mitigation Program

In [14]:
ls_fema = pd.read_csv(r'Datasets/database.csv')

**Checking dataset information - Features and ammount of data**

In [15]:
ls_fema.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46185 entries, 0 to 46184
Data columns (total 14 columns):
Declaration Number                  46185 non-null object
Declaration Type                    46185 non-null object
Declaration Date                    46185 non-null object
State                               46185 non-null object
County                              45988 non-null object
Disaster Type                       46185 non-null object
Disaster Title                      46185 non-null object
Start Date                          46185 non-null object
End Date                            45843 non-null object
Close Date                          35210 non-null object
Individual Assistance Program       46185 non-null object
Individuals & Households Program    46185 non-null object
Public Assistance Program           46185 non-null object
Hazard Mitigation Program           46185 non-null object
dtypes: object(14)
memory usage: 4.9+ MB

**Data starts in 1953/May up to 2017/Feb**

In [16]:
ls_fema.head()

,Declaration Number,Declaration Type,Declaration Date,State,County,Disaster Type,Disaster Title,Start Date,End Date,Close Date,Individual Assistance Program,Individuals & Households Program,Public Assistance Program,Hazard Mitigation Program
0,DR-1,Disaster,05/02/1953,GA,NaN,Tornado,Tornado,05/02/1953,05/02/1953,06/01/1954,Yes,No,Yes,Yes
1,DR-2,Disaster,05/15/1953,TX,NaN,Tornado,Tornado and Heavy Rainfall,05/15/1953,05/15/1953,01/01/1958,Yes,No,Yes,Yes
2,DR-3,Disaster,05/29/1953,LA,NaN,Flood,Flood,05/29/1953,05/29/1953,02/01/1960,Yes,No,Yes,Yes
3,DR-4,Disaster,06/02/1953,MI,NaN,Tornado,Tornado,06/02/1953,06/02/1953,02/01/1956,Yes,No,Yes,Yes
4,DR-5,Disaster,06/06/1953,MT,NaN,Flood,Floods,06/06/1953,06/06/1953,12/01/1955,Yes,No,Yes,Yes

In [17]:
ls_fema.tail()

,Declaration Number,Declaration Type,Declaration Date,State,County,Disaster Type,Disaster Title,Start Date,End Date,Close Date,Individual Assistance Program,Individuals & Households Program,Public Assistance Program,Hazard Mitigation Program
46180,DR-4301,Disaster,02/14/2017,CA,Sutter County,Storm,"Severe Winter Storms, Flooding, and Mudslides",01/03/2017,01/12/2017,NaN,No,No,Yes,Yes
46181,DR-4301,Disaster,02/14/2017,CA,Trinity County,Storm,"Severe Winter Storms, Flooding, and Mudslides",01/03/2017,01/12/2017,NaN,No,No,Yes,Yes
46182,DR-4301,Disaster,02/14/2017,CA,Tuolumne County,Storm,"Severe Winter Storms, Flooding, and Mudslides",01/03/2017,01/12/2017,NaN,No,No,Yes,Yes
46183,DR-4301,Disaster,02/14/2017,CA,Yolo County,Storm,"Severe Winter Storms, Flooding, and Mudslides",01/03/2017,01/12/2017,NaN,No,No,Yes,Yes
46184,DR-4301,Disaster,02/14/2017,CA,Yuba County,Storm,"Severe Winter Storms, Flooding, and Mudslides",01/03/2017,01/12/2017,NaN,No,No,Yes,Yes

**Disaster Types**

In [18]:
ls_fema['Disaster Type'].value_counts()

Storm              16250
Flood               9317
Hurricane           8764
Snow                3565
Fire                2647
Ice                 1970
Tornado             1412
Drought             1292
Winter               301
Other                297
Typhoon              119
Earthquake           105
Volcano               50
Water                 42
Chemical              18
Mud/Landslide         10
Tsunami                9
Dam/Levee Break        6
Human Cause            6
Terrorism              5
Name: Disaster Type, dtype: int64

In [19]:
ls_fema['Disaster Title'].value_counts()

Severe Storms and Flooding                                     6817
Severe Storms, Tornadoes, and Flooding                         3229
Hurricane Katrina Evacuation                                   2602
Severe Winter Storm                                            1887
Flooding                                                       1232
Drought                                                        1014
Severe Winter Storms                                            844
Severe Storms, Tornadoes, Straight-Line Winds, and Flooding     827
Wildfires                                                       610
Snow                                                            602
Heavy Rains and Flooding                                        595
Severe Storms, Flooding, and Tornadoes                          573
Severe Storms and Tornadoes                                     568
Hurricane Sandy                                                 559
Hurricane Irene                                                 488
Severe Winter Storm and Snowstorm                               469
Severe Winter Ice Storm                                         420
Severe Winter Storms and Flooding                               365
Extreme Wildfire Threat                                         331
Hurricane Rita                                                  319
Hurricane Rita                                                  318
Hurricane Gustav                                                304
Hurricane Katrina                                               303
Hurricane Matthew                                               295
Severe Snowfall and Winter Storm                                282
Tornadoes                                                       266
Blizzard of 96 (Severe Snow Storm)                              264
Tropical Storm Charley                                          257
Tropical Storm Agnes                                            256
Blizzard of 96                                                  255
                                                               ...
Mustang Road Fire                                                 1
Severe Storms, High Surf, and Flooding                            1
Gage Holland Fire                                                 1
Tanglewood Fire Complex                                           1
Sd - Mill Road Wildfire - 11/19/2003                              1
Typhoon Mitag                                                     1
Little Lewis Fire                                                 1
Rodeo Fire                                                        1
Al - Martin School Fire - 09/18/1999                              1
Wy - Tongue River Wildfire - 11/19/2003                           1
Beaver Creek Fire                                                 1
Va - Shenandoah Gap Fire Complex - 11/20/01                       1
Warehouse Fire                                                    1
Carbon Fire                                                       1
Lower North Fork Fire                                             1
Parker Fire                                                       1
Deep Harbor Fire                                                  1
Volcano                                                           1
Co-Wiley Ridge Fire-06/23/02                                      1
Nv - Gondola Fire - 07/03/2002                                    1
Puako Fire                                                        1
Ut-Causey Fire 07/14/2003                                         1
Frankhoma 81-Fire                                                 1
Timbered Rock Fire                                                1
Mt-Wedge Canyon Fire-07/18/2003                                   1
Midwest City Fire Complex                                         1
Midwest Choctaw Fire                                              1
Nm - Penasco Fire - 05-01-02                                      1
Powerline Fire                                                    1
Az-Ryan-Wildfire-4/30/2002                                        1
Name: Disaster Title, Length: 1489, dtype: int64

In [38]:
ls_fema[ls_fema['Disaster Title'].str.contains('Landslide')]

,Declaration Number,Declaration Type,Declaration Date,State,County,Disaster Type,Disaster Title,Start Date,End Date,Close Date,Individual Assistance Program,Individuals & Households Program,Public Assistance Program,Hazard Mitigation Program
1708,DR-281,Disaster,12/19/1969,AK,Tanana ANV/ANVSA,Storm,Heavy Rains and Landslide,12/19/1969,12/19/1969,08/16/1971,Yes,No,Yes,Yes
3291,DR-396,Disaster,07/06/1973,CO,Alamosa County,Flood,Flooding and Landslides,07/06/1973,07/06/1973,09/16/1976,No,No,Yes,Yes
3292,DR-396,Disaster,07/06/1973,CO,Archuleta County,Flood,Flooding and Landslides,07/06/1973,07/06/1973,09/16/1976,No,No,Yes,Yes
3293,DR-396,Disaster,07/06/1973,CO,Conejos County,Flood,Flooding and Landslides,07/06/1973,07/06/1973,09/16/1976,No,No,Yes,Yes
3294,DR-396,Disaster,07/06/1973,CO,Costilla County,Flood,Flooding and Landslides,07/06/1973,07/06/1973,09/16/1976,No,No,Yes,Yes
3295,DR-396,Disaster,07/06/1973,CO,Delta County,Flood,Flooding and Landslides,07/06/1973,07/06/1973,09/16/1976,No,No,Yes,Yes
3296,DR-396,Disaster,07/06/1973,CO,Dolores County,Flood,Flooding and Landslides,07/06/1973,07/06/1973,09/16/1976,No,No,Yes,Yes
3297,DR-396,Disaster,07/06/1973,CO,Gunnison County,Flood,Flooding and Landslides,07/06/1973,07/06/1973,09/16/1976,No,No,Yes,Yes
3298,DR-396,Disaster,07/06/1973,CO,Hinsdale County,Flood,Flooding and Landslides,07/06/1973,07/06/1973,09/16/1976,No,No,Yes,Yes
3299,DR-396,Disaster,07/06/1973,CO,La Plata County,Flood,Flooding and Landslides,07/06/1973,07/06/1973,09/16/1976,No,No,Yes,Yes
3300,DR-396,Disaster,07/06/1973,CO,Mineral County,Flood,Flooding and Landslides,07/06/1973,07/06/1973,09/16/1976,No,No,Yes,Yes
3301,DR-396,Disaster,07/06/1973,CO,Montezuma County,Flood,Flooding and Landslides,07/06/1973,07/06/1973,09/16/1976,No,No,Yes,Yes
3302,DR-396,Disaster,07/06/1973,CO,Montrose County,Flood,Flooding and Landslides,07/06/1973,07/06/1973,09/16/1976,No,No,Yes,Yes
3303,DR-396,Disaster,07/06/1973,CO,Ouray County,Flood,Flooding and Landslides,07/06/1973,07/06/1973,09/16/1976,No,No,Yes,Yes
3304,DR-396,Disaster,07/06/1973,CO,Rio Grande County,Flood,Flooding and Landslides,07/06/1973,07/06/1973,09/16/1976,No,No,Yes,Yes
3305,DR-396,Disaster,07/06/1973,CO,San Juan County,Flood,Flooding and Landslides,07/06/1973,07/06/1973,09/16/1976,No,No,Yes,Yes
3306,DR-396,Disaster,07/06/1973,CO,San Miguel County,Flood,Flooding and Landslides,07/06/1973,07/06/1973,09/16/1976,No,No,Yes,Yes
3307,DR-397,Disaster,07/06/1973,VT,Addison County,Flood,"Severe Storms, Flooding, and Landslides",07/06/1973,07/06/1973,11/12/1976,Yes,No,Yes,Yes
3308,DR-397,Disaster,07/06/1973,VT,Bennington County,Flood,"Severe Storms, Flooding, and Landslides",07/06/1973,07/06/1973,11/12/1976,Yes,No,Yes,Yes
3309,DR-397,Disaster,07/06/1973,VT,Caledonia County,Flood,"Severe Storms, Flooding, and Landslides",07/06/1973,07/06/1973,11/12/1976,Yes,No,Yes,Yes
3310,DR-397,Disaster,07/06/1973,VT,Chittenden County,Flood,"Severe Storms, Flooding, and Landslides",07/06/1973,07/06/1973,11/12/1976,Yes,No,Yes,Yes
3311,DR-397,Disaster,07/06/1973,VT,Essex County,Flood,"Severe Storms, Flooding, and Landslides",07/06/1973,07/06/1973,11/12/1976,Yes,No,Yes,Yes
3312,DR-397,Disaster,07/06/1973,VT,Franklin County,Flood,"Severe Storms, Flooding, and Landslides",07/06/1973,07/06/1973,11/12/1976,Yes,No,Yes,Yes
3313,DR-397,Disaster,07/06/1973,VT,Grand Isle County,Flood,"Severe Storms, Flooding, and Landslides",07/06/1973,07/06/1973,11/12/1976,Yes,No,Yes,Yes
3314,DR-397,Disaster,07/06/1973,VT,Lamoille County,Flood,"Severe Storms, Flooding, and Landslides",07/06/1973,07/06/1973,11/12/1976,Yes,No,Yes,Yes
3315,DR-397,Disaster,07/06/1973,VT,Orange County,Flood,"Severe Storms, Flooding, and Landslides",07/06/1973,07/06/1973,11/12/1976,Yes,No,Yes,Yes
3316,DR-397,Disaster,07/06/1973,VT,Orleans County,Flood,"Severe Storms, Flooding, and Landslides",07/06/1973,07/06/1973,11/12/1976,Yes,No,Yes,Yes
3317,DR-397,Disaster,07/06/1973,VT,Rutland County,Flood,"Severe Storms, Flooding, and Landslides",07/06/1973,07/06/1973,11/12/1976,Yes,No,Yes,Yes
3318,DR-397,Disaster,07/06/1973,VT,Washington County,Flood,"Severe Storms, Flooding, and Landslides",07/06/1973,07/06/1973,11/12/1976,Yes,No,Yes,Yes
3319,DR-397,Disaster,07/06/1973,VT,Windham County,Flood,"Severe Storms, Flooding, and Landslides",07/06/1973,07/06/1973,11/12/1976,Yes,No,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45614,DR-4273,Disaster,06/25/2016,WV,Monroe County,Flood,"Severe Storms, Flooding, Landslides, and Mudsl...",06/22/2016,06/29/2016,NaN,No,Yes,Yes,Yes
45615,DR-4273,Disaster,06/25/2016,WV,Nicholas County,Flood,"Severe Storms, Flooding, Landslides, and Mudsl...",06/22/2016,06/29/2016,NaN,No,Yes,Yes,Yes
45616,DR-4273,Disaster,06/25/2016,WV,Pocahontas County,Flood,"Severe Storms, Flooding, Landslides, and Mudsl...",06/22/2016,06/29/2016,NaN,No,Yes,Yes,Yes
45617,DR-4273,Disaster,06/25/2016,WV,Randolph County,Flood,"Severe Storms, Flooding, Landslides, and Mudsl...",06/22/2016,06/29/2016,NaN,No,Yes,Yes,Yes
45618,DR-4273,Disaster,06/25/2016,WV,Roane County,Flood,"Severe Storms, Flooding, Landslides, and Mudsl...",06/22/2016,06/29/2016,NaN,No,Yes,Yes,Yes
45619,DR-4273,Disaster,06/25/2016,WV,Summers County,Flood,"Severe Storms, Flooding, Landslides, and Mudsl...",06/22/2016,06/29/2016,NaN,No,Yes,Yes,Yes
45620,DR-4273,Disaster,06/25/2016,WV,Upshur County,Flood,"Severe Storms, Flooding, Landslides, and Mudsl...",06/22/2016,06/29/2016,NaN,No,Yes,Yes,Yes
45621,DR-4273,Disaster,06/25/2016,WV,Wayne County,Flood,"Severe Storms, Flooding, Landslides, and Mudsl...",06/22/2016,06/29/2016,NaN,No,Yes,Yes,Yes
45622,DR-4273,Disaster,06/25/2016,WV,Webster County,Flood,"Severe Storms, Flooding, Landslides, and Mudsl...",06/22/2016,06/29/2016,NaN,No,Yes,Yes,Yes
45667,DR-4278,Disaster,08/26/2016,KY,Adair County,Storm,"Severe Storm, Tornadoes, Flooding, Landslides,...",07/02/2016,07/09/2016,NaN,No,No,Yes,Yes
45668,DR-4278,Disaster,08/26/2016,KY,Butler County,Storm,"Severe Storm, Tornadoes, Flooding, Landslides,...",07/02/2016,07/09/2016,NaN,No,No,Yes,Yes
45669,DR-4278,Disaster,08/26/2016,KY,Caldwell County,Storm,"Severe Storm, Tornadoes, Flooding, Landslides,...",07/02/2016,07/09/2016,NaN,No,No,Yes,Yes
45670,DR-4278,Disaster,08/26/2016,KY,Calloway County,Storm,"Severe Storm, Tornadoes, Flooding, Landslides,...",07/02/2016,07/09/2016,NaN,No,No,Yes,Yes
45671,DR-4278,Disaster,08/26/2016,KY,Christian County,Storm,"Severe Storm, Tornadoes, Flooding, Landslides,...",07/02/2016,07/09/2016,NaN,No,No,Yes,Yes
45672,DR-4278,Disaster,08/26/2016,KY,Clay County,Storm,"Severe Storm, Tornadoes, Flooding, Landslides,...",07/02/2016,07/09/2016,NaN,No,No,Yes,Yes
45673,DR-4278,Disaster,08/26/2016,KY,Crittenden County,Storm,"Severe Storm, Tornadoes, Flooding, Landslides,...",07/02/2016,07/09/2016,NaN,No,No,Yes,Yes
45674,DR-4278,Disaster,08/26/2016,KY,Daviess County,Storm,"Severe Storm, Tornadoes, Flooding, Landslides,...",07/02/2016,07/09/2016,NaN,No,No,Yes,Yes
45675,DR-4278,Disaster,08/26/2016,KY,Edmonson County,Storm,"Severe Storm, Tornadoes, Flooding, Landslides,...",07/02/2016,07/09/2016,NaN,No,No,Yes,Yes
45676,DR-4278,Disaster,08/26/2016,KY,Hart County,Storm,"Severe Storm, Tornadoes, Flooding, Landslides,...",07/02/2016,07/09/2016,NaN,No,No,Yes,Yes
45677,DR-4278,Disaster,08/26/2016,KY,Hopkins County,Storm,"Severe Storm, Tornadoes, Flooding, Landslides,...",07/02/2016,07/09/2016,NaN,No,No,Yes,Yes
45678,DR-4278,Disaster,08/26/2016,KY,Livingston County,Storm,"Severe Storm, Tornadoes, Flooding, Landslides,...",07/02/2016,07/09/2016,NaN,No,No,Yes,Yes
45679,DR-4278,Disaster,08/26/2016,KY,Lyon County,Storm,"Severe Storm, Tornadoes, Flooding, Landslides,...",07/02/2016,07/09/2016,NaN,No,No,Yes,Yes
45680,DR-4278,Disaster,08/26/2016,KY,Marshall County,Storm,"Severe Storm, Tornadoes, Flooding, Landslides,...",07/02/2016,07/09/2016,NaN,No,No,Yes,Yes
45681,DR-4278,Disaster,08/26/2016,KY,Metcalfe County,Storm,"Severe Storm, Tornadoes, Flooding, Landslides,...",07/02/2016,07/09/2016,NaN,No,No,Yes,Yes
45682,DR-4278,Disaster,08/26/2016,KY,Ohio County,Storm,"Severe Storm, Tornadoes, Flooding, Landslides,...",07/02/2016,07/09/2016,NaN,No,No,Yes,Yes
45683,DR-4278,Disaster,08/26/2016,KY,Todd County,Storm,"Severe Storm, Tornadoes, Flooding, Landslides,...",07/02/2016,07/09/2016,NaN,No,No,Yes,Yes
45684,DR-4278,Disaster,08/26/2016,KY,Trigg County,Storm,"Severe Storm, Tornadoes, Flooding, Landslides,...",07/02/2016,07/09/2016,NaN,No,No,Yes,Yes
45685,DR-4278,Disaster,08/26/2016,KY,Union County,Storm,"Severe Storm, Tornadoes, Flooding, Landslides,...",07/02/2016,07/09/2016,NaN,No,No,Yes,Yes
45686,DR-4278,Disaster,08/26/2016,KY,Webster County,Storm,"Severe Storm, Tornadoes, Flooding, Landslides,...",07/02/2016,07/09/2016,NaN,No,No,Yes,Yes
45799,DR-4282,Disaster,10/06/2016,HI,Maui County,Mud/Landslide,"Severe Storms, Flooding, Landslides, and Mudsl...",09/11/2016,09/14/2016,NaN,No,No,Yes,Yes

## Natural disaster data - Kaggle

Content  
This dataset contains information on global occurrences of natural disasters and the economic damage caused by them. The included types of natural disaster are 'Drought', 'Earthquake', 'Extreme temperature', 'Extreme weather', 'Flood', 'Impact', 'Landslide', 'Mass movement (dry)', 'Volcanic activity' and 'Wildfire'. It also includes information on all these natural disasters combined. The time period is 1900-2018 with several missing values.

This dataset is a subset of the data available on https://ourworldindata.org/natural-disasters

Acknowledgements  
Thanks to https://ourworldindata.org/natural-disasters (data published by EMDAT (2019): OFDA/CRED International Disaster Database, Universit√© catholique de Louvain ‚Äì Brussels ‚Äì Belgium) for the data.

Other links:

https://ourworldindata.org/ofdacred-international-disaster-data  
https://ourworldindata.org/natural-disasters

Data Sources  
economic-damage-from-natural-disasters.csv - 4 columns  
number-of-natural-disaster-events.csv - 4 columns  

About this file  
No description yet

Columns
- Entity
- Code
- Year
- Total economic damage from natural disasters (US$)

In [39]:
ls_ourworldindata_economic = pd.read_csv(r'Datasets/economic-damage-from-natural-disasters.csv')
ls_ourworldindata_numbers = pd.read_csv(r'Datasets/number-of-natural-disaster-events.csv')

In [40]:
ls_ourworldindata_economic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 561 entries, 0 to 560
Data columns (total 4 columns):
Entity                                                561 non-null object
Code                                                  0 non-null float64
Year                                                  561 non-null int64
Total economic damage from natural disasters (US$)    561 non-null int64
dtypes: float64(1), int64(2), object(1)
memory usage: 17.6+ KB

In [41]:
ls_ourworldindata_economic.head()

,Entity,Code,Year,Total economic damage from natural disasters (US$)
0,All natural disasters,NaN,1900,30000000
1,All natural disasters,NaN,1901,0
2,All natural disasters,NaN,1902,0
3,All natural disasters,NaN,1903,480000000
4,All natural disasters,NaN,1904,0

In [42]:
ls_ourworldindata_economic.tail()

       Entity  Code  Year  Total economic damage from natural disasters (US$)
556  Wildfire   NaN  2014                                          259000000
557  Wildfire   NaN  2015                                         3439820000
558  Wildfire   NaN  2016                                         6287000000
559  Wildfire   NaN  2017                                         1019000000
560  Wildfire   NaN  2018                                        22745000000

In [43]:
ls_ourworldindata_numbers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 828 entries, 0 to 827
Data columns (total 4 columns):
Entity                                                       828 non-null object
Code                                                         0 non-null float64
Year                                                         828 non-null int64
Number of reported natural disasters (reported disasters)    828 non-null int64
dtypes: float64(1), int64(2), object(1)
memory usage: 26.0+ KB

In [44]:
ls_ourworldindata_numbers.head()

,Entity,Code,Year,Number of reported natural disasters (reported disasters)
0,All natural disasters,NaN,1900,5
1,All natural disasters,NaN,1901,2
2,All natural disasters,NaN,1902,9
3,All natural disasters,NaN,1903,8
4,All natural disasters,NaN,1904,2

In [45]:
ls_ourworldindata_numbers.tail()

,Entity,Code,Year,Number of reported natural disasters (reported disasters)
823,Wildfire,NaN,2014,4
824,Wildfire,NaN,2015,12
825,Wildfire,NaN,2016,10
826,Wildfire,NaN,2017,13
827,Wildfire,NaN,2018,10